<div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto">
            <div class="jumbotron">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO-пригодность</p>

                <form action="/urls" method="post" class="rss-form d-flex justify-content-center">
                    <input type="text" name="url" aria-label="url" class="form-control form-control-lg" placeholder="https://www.example.com" required>
                    <button type="submit" class="btn btn-lg btn-primary ms-3 px-5 text-uppercase">Проверить</button>
                </form>
            </div>
        </div>
    </div>
</div>