<div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto">
            <div class="jumbotron">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO-пригодность</p>

                <?php if (isset($_SESSION['flash'])): ?>
                    <div class="alert alert-<?= $_SESSION['flash']['type'] ?> alert-dismissible fade show" role="alert">
                        <?= htmlspecialchars($_SESSION['flash']['message']) ?>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    <?php unset($_SESSION['flash']); ?>
                <?php endif; ?>

                <form action="/urls" method="post" class="d-flex justify-content-center">
                    <input type="text" name="url" aria-label="url" class="form-control form-control-lg" placeholder="https://www.example.com" required>
                    <button type="submit" class="btn btn-lg btn-primary ms-3 px-5 text-uppercase">Проверить</button>
                </form>
            </div>
        </div>
    </div>
</div>